# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SalesHack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SalesHack
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'SalesHackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SalesHack-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SalesHack-tvOS

  target 'SalesHack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
